In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings(action='ignore')

### 전처리된 데이터 불러오기

In [3]:
baby_growth_df = pd.read_csv("./baby_growth_df.csv")
baby_growth_df

days  height  weight  gender
0         0    52.0    3.78       1
1         0    52.0    3.78       1
2         0    50.0    3.20       1
3         1    51.0    2.45       1
4         1    50.0    2.80       1
...     ...     ...     ...     ...
79344   365    74.6    9.60       0
79345   365    74.6    8.60       0
79346   365    74.6    9.40       0
79347   365    74.6    9.40       0
79348   365    74.6    8.20       0

[79349 rows x 4 columns]

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

### 단순선형회귀 - 선택

In [5]:
# 현재 생후 일 수
current_days = int(input("현재 생후 일 수를 입력하세요: "))

# 현재 키, 몸무게, 성별 입력
current_height = float(input("현재 키를 입력하세요: "))
current_weight = float(input("현재 몸무게를 입력하세요: "))
input_gender = input("아기의 성별을 입력하세요 (M/F): ")

if input_gender == 'F':
    gender = 0
elif input_gender == 'M':
    gender = 1
else:
    print("성별은 'F' 또는 'M' 중에서 입력해주세요.")
    exit()
# 해당 성별에 해당하는 데이터 필터링
filtered_df = baby_growth_df[baby_growth_df['gender'] == gender]

# 키에 대한 예측 모델 학습
height_X = filtered_df['days'].values.reshape(-1, 1)
height_y = filtered_df['height'].values

# 데이터 분할
# height_X_train, height_X_test, height_y_train, height_y_test = train_test_split(height_X, height_y, test_size=0.2, random_state=42)

height_model = LinearRegression()
height_model.fit(height_X, height_y)

# 몸무게에 대한 예측 모델 학습
weight_X = filtered_df['days'].values.reshape(-1, 1)
weight_y = filtered_df['weight'].values

# 데이터 분할
# weight_X_train, weight_X_test, weight_y_train, weight_y_test = train_test_split(weight_X, weight_y, test_size=0.2, random_state=42)

weight_model = LinearRegression()
weight_model.fit(weight_X, weight_y)

LinearRegression()

In [6]:
# 예측에 사용할 일 수 범위
prediction_range = range(1, 181)

predicted_heights = []

# 입력한 일 수에 대한 예측값 계산
predicted_height = height_model.predict([[current_days]])
print("current height = ", current_height)
print("predicted_height = ", predicted_height)

if current_height > predicted_height:
    slope_height = height_model.coef_[0]
    print("slope_height = ", slope_height)
    for days in prediction_range:
        prediction_days = current_days + days
        predicted_height_sync = slope_height * prediction_days + (height_model.intercept_ + (current_height - predicted_height))
        predicted_heights.append(predicted_height_sync)
else:
    slope_height = height_model.coef_[0]
    for days in prediction_range:
        prediction_days = current_days + days
        predicted_height_sync = slope_height * prediction_days + (height_model.intercept_ - (predicted_height - current_height))
        predicted_heights.append(predicted_height_sync)

predicted_heights

current height =  65.0
predicted_height =  [66.09668543]


[array([65.08434233]),
 array([65.16868466]),
 array([65.25302699]),
 array([65.33736932]),
 array([65.42171165]),
 array([65.50605398]),
 array([65.59039631]),
 array([65.67473864]),
 array([65.75908097]),
 array([65.8434233]),
 array([65.92776563]),
 array([66.01210796]),
 array([66.09645029]),
 array([66.18079262]),
 array([66.26513495]),
 array([66.34947728]),
 array([66.43381961]),
 array([66.51816194]),
 array([66.60250427]),
 array([66.6868466]),
 array([66.77118893]),
 array([66.85553126]),
 array([66.93987359]),
 array([67.02421592]),
 array([67.10855825]),
 array([67.19290058]),
 array([67.27724291]),
 array([67.36158523]),
 array([67.44592756]),
 array([67.53026989]),
 array([67.61461222]),
 array([67.69895455]),
 array([67.78329688]),
 array([67.86763921]),
 array([67.95198154]),
 array([68.03632387]),
 array([68.1206662]),
 array([68.20500853]),
 array([68.28935086]),
 array([68.37369319]),
 array([68.45803552]),
 array([68.54237785]),
 array([68.62672018]),
 array([68.711

In [7]:
predicted_heights_val = []
for i in range(len(predicted_heights)):
    predicted_heights_val.append(round(predicted_heights[i][0],2))
predicted_heights_val

[65.08,
 65.17,
 65.25,
 65.34,
 65.42,
 65.51,
 65.59,
 65.67,
 65.76,
 65.84,
 65.93,
 66.01,
 66.1,
 66.18,
 66.27,
 66.35,
 66.43,
 66.52,
 66.6,
 66.69,
 66.77,
 66.86,
 66.94,
 67.02,
 67.11,
 67.19,
 67.28,
 67.36,
 67.45,
 67.53,
 67.61,
 67.7,
 67.78,
 67.87,
 67.95,
 68.04,
 68.12,
 68.21,
 68.29,
 68.37,
 68.46,
 68.54,
 68.63,
 68.71,
 68.8,
 68.88,
 68.96,
 69.05,
 69.13,
 69.22,
 69.3,
 69.39,
 69.47,
 69.55,
 69.64,
 69.72,
 69.81,
 69.89,
 69.98,
 70.06,
 70.14,
 70.23,
 70.31,
 70.4,
 70.48,
 70.57,
 70.65,
 70.74,
 70.82,
 70.9,
 70.99,
 71.07,
 71.16,
 71.24,
 71.33,
 71.41,
 71.49,
 71.58,
 71.66,
 71.75,
 71.83,
 71.92,
 72.0,
 72.08,
 72.17,
 72.25,
 72.34,
 72.42,
 72.51,
 72.59,
 72.68,
 72.76,
 72.84,
 72.93,
 73.01,
 73.1,
 73.18,
 73.27,
 73.35,
 73.43,
 73.52,
 73.6,
 73.69,
 73.77,
 73.86,
 73.94,
 74.02,
 74.11,
 74.19,
 74.28,
 74.36,
 74.45,
 74.53,
 74.62,
 74.7,
 74.78,
 74.87,
 74.95,
 75.04,
 75.12,
 75.21,
 75.29,
 75.37,
 75.46,
 75.54,
 75.63,
 75

In [8]:
print(len(predicted_heights_val))

180


In [9]:
# 예측에 사용할 일 수 범위
prediction_range = range(1, 181)

# 예측 결과를 저장할 리스트 초기화
predicted_weights = []

# 입력한 일 수에 대한 예측값 계산
predicted_weight = weight_model.predict([[current_days]])
print("current weight = ", current_weight)
print("predicted_weight = ", predicted_weight)


if current_weight > predicted_weight:
    slope_weight = weight_model.coef_[0]
    print("slope_weight = ", slope_weight)
    for days in prediction_range:
        prediction_days = current_days + days
        predicted_weight_sync = slope_weight * prediction_days + (weight_model.intercept_ + (current_weight - predicted_weight))
        predicted_weights.append(predicted_weight_sync)
else:
    slope_weight = weight_model.coef_[0]
    print("slope_weight = ", slope_weight)
    for days in prediction_range:
        prediction_days = current_days + days
        predicted_weight_sync = slope_weight * prediction_days + (weight_model.intercept_ - (predicted_weight - current_weight))
        predicted_weights.append(predicted_weight_sync)
        
predicted_weights

current weight =  9.0
predicted_weight =  [7.69398139]
slope_weight =  0.023312481659303996


[array([9.02331248]),
 array([9.04662496]),
 array([9.06993744]),
 array([9.09324993]),
 array([9.11656241]),
 array([9.13987489]),
 array([9.16318737]),
 array([9.18649985]),
 array([9.20981233]),
 array([9.23312482]),
 array([9.2564373]),
 array([9.27974978]),
 array([9.30306226]),
 array([9.32637474]),
 array([9.34968722]),
 array([9.37299971]),
 array([9.39631219]),
 array([9.41962467]),
 array([9.44293715]),
 array([9.46624963]),
 array([9.48956211]),
 array([9.5128746]),
 array([9.53618708]),
 array([9.55949956]),
 array([9.58281204]),
 array([9.60612452]),
 array([9.629437]),
 array([9.65274949]),
 array([9.67606197]),
 array([9.69937445]),
 array([9.72268693]),
 array([9.74599941]),
 array([9.76931189]),
 array([9.79262438]),
 array([9.81593686]),
 array([9.83924934]),
 array([9.86256182]),
 array([9.8858743]),
 array([9.90918678]),
 array([9.93249927]),
 array([9.95581175]),
 array([9.97912423]),
 array([10.00243671]),
 array([10.02574919]),
 array([10.04906167]),
 array([10.0

In [10]:
predicted_weights_val = []
for i in range(len(predicted_weights)):
    predicted_weights_val.append(round(predicted_weights[i][0],2))
predicted_weights_val

[9.02,
 9.05,
 9.07,
 9.09,
 9.12,
 9.14,
 9.16,
 9.19,
 9.21,
 9.23,
 9.26,
 9.28,
 9.3,
 9.33,
 9.35,
 9.37,
 9.4,
 9.42,
 9.44,
 9.47,
 9.49,
 9.51,
 9.54,
 9.56,
 9.58,
 9.61,
 9.63,
 9.65,
 9.68,
 9.7,
 9.72,
 9.75,
 9.77,
 9.79,
 9.82,
 9.84,
 9.86,
 9.89,
 9.91,
 9.93,
 9.96,
 9.98,
 10.0,
 10.03,
 10.05,
 10.07,
 10.1,
 10.12,
 10.14,
 10.17,
 10.19,
 10.21,
 10.24,
 10.26,
 10.28,
 10.31,
 10.33,
 10.35,
 10.38,
 10.4,
 10.42,
 10.45,
 10.47,
 10.49,
 10.52,
 10.54,
 10.56,
 10.59,
 10.61,
 10.63,
 10.66,
 10.68,
 10.7,
 10.73,
 10.75,
 10.77,
 10.8,
 10.82,
 10.84,
 10.86,
 10.89,
 10.91,
 10.93,
 10.96,
 10.98,
 11.0,
 11.03,
 11.05,
 11.07,
 11.1,
 11.12,
 11.14,
 11.17,
 11.19,
 11.21,
 11.24,
 11.26,
 11.28,
 11.31,
 11.33,
 11.35,
 11.38,
 11.4,
 11.42,
 11.45,
 11.47,
 11.49,
 11.52,
 11.54,
 11.56,
 11.59,
 11.61,
 11.63,
 11.66,
 11.68,
 11.7,
 11.73,
 11.75,
 11.77,
 11.8,
 11.82,
 11.84,
 11.87,
 11.89,
 11.91,
 11.94,
 11.96,
 11.98,
 12.01,
 12.03,
 12.05,
 12.08,

In [11]:
print(len(predicted_weights_val))

180


In [12]:
# 결과 출력
print(f"아기의 1개월 뒤 예상 키는 {predicted_heights_val[29]:.1f}cm 입니다.")
print(f"아기의 3개월 뒤 예상 키는 {predicted_heights_val[89]:.1f}cm 입니다.")
print(f"아기의 6개월 뒤 예상 키는 {predicted_heights_val[179]:.1f}cm 입니다.")
print(f"아기의 1개월 뒤 예상 몸무게는 {predicted_weights_val[29]:.1f}kg 입니다.")
print(f"아기의 3개월 뒤 예상 몸무게는 {predicted_weights_val[89]:.1f}kg 입니다.")
print(f"아기의 6개월 뒤 예상 몸무게는 {predicted_weights_val[179]:.1f}kg 입니다.")

아기의 1개월 뒤 예상 키는 67.5cm 입니다.
아기의 3개월 뒤 예상 키는 72.6cm 입니다.
아기의 6개월 뒤 예상 키는 80.2cm 입니다.
아기의 1개월 뒤 예상 몸무게는 9.7kg 입니다.
아기의 3개월 뒤 예상 몸무게는 11.1kg 입니다.
아기의 6개월 뒤 예상 몸무게는 13.2kg 입니다.
